name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /nologo /clp:NoSummary

      - name: Run Tests
        run: >
          dotnet test
          -p:CollectCoverage=true
          -p:CoverletOutput=TestResults/
          -p:CoverletOutputFormat=opencover
          -p:BuildInParallel=false
          -m:1
          --configuration Release
          --no-build
        env:
          Nordigen__BaseAddress: https://ob.nordigen.com/
          Nordigen__SecretId: ${{ secrets.NORDIGEN_SECRET_ID }}
          Nordigen__SecretKey: ${{ secrets.NORDIGEN_SECRET_KEY }}

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.2.2
        with:
          solution: NordigenDotNet.sln

      - name: Gather Code Coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: true
