name: Run tests

on:
  schedule:
    - cron: "0 0 * * 1-5"

  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-dotnet@v3.0.0
      - run: dotnet restore

      - name: Build
        run: >
          dotnet build
          --configuration Release
          --no-restore
          /warnAsError
          /nologo
          /clp:NoSummary

      - name: Run Tests
        run: >
          dotnet test
          -p:CollectCoverage=true
          -p:CoverletOutput=TestResults/
          -p:CoverletOutputFormat=opencover
          --configuration Release
          --no-build
        env:
          Nordigen__SecretId: ${{ secrets.NORDIGEN_SECRET_ID }}
          Nordigen__SecretKey: ${{ secrets.NORDIGEN_SECRET_KEY }}

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.2.3
        with:
          solution: NordigenDotNet.sln
          resharper-version: 2022.1.2
          treat-warnings-as-errors: true

      - name: Gather Code Coverage
        if: github.event.schedule == null
        uses: codecov/codecov-action@v3.1.1
        with:
          fail_ci_if_error: true
